name: Checks
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # typecheck: -> TODO
  # format: -> TODO
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
      - run: npm run lint
